# Generated by Django 4.0.4 on 2022-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Recipe title', max_length=20)),
                ('desc', models.CharField(help_text='Recipe description', max_length=250)),
            ],
        ),
    ]
