# Generated by Django 4.0.4 on 2022-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ingredient title', max_length=20)),
                ('recipes', models.ManyToManyField(to='recipes.recipemodel')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
