# Generated by Django 4.0.4 on 2022-05-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipemodel_options_ingredientmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientmodel',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredientmodel'),
        ),
    ]
