# Generated by Django 4.0.4 on 2022-05-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredientmodel_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmodel',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientmodel',
            name='measure_unit',
            field=models.CharField(default='gr', help_text='Measure unit', max_length=4),
            preserve_default=False,
        ),
    ]
